<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Enums\NotificationType;
use Carbon\Carbon;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable, TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'avatar',
        'nickname',
        'bio',
        'language_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'two_factor_secret',
        'two_factor_recovery_codes',
        'remember_token',
    ];

    /*
     * Checks if a user belongs to a chat room (more specifically a project for now)
     */
    public function isMemberOfRoom(int $id): bool
    {
        $chatRoom = ChatRoom::find($id);

        return $chatRoom->project->userIsMember($this);
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'two_factor_confirmed_at' => 'datetime',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (User $user) {
            $user->preferences()->create([

            ]);
        });
    }

    /**
     * Get a user's preferences on the app (lang(s), location, etc.)
     */
    public function preferences(): HasOne
    {
        return $this->hasOne(UserPreferences::class);
    }

    /**
     * Get a user's tasks participation.
     */
    public function tasks(): BelongsToMany
    {
        return $this
            ->belongsToMany(Task::class, Participation::class)
            ->orderBy('due_at', 'asc');
    }

    /**
     * Get a user's upcoming tasks.
     */
    public function upcomingTasks(): BelongsToMany
    {
        return $this
            ->tasks()
            ->where('due_at', '>=', Carbon::now())
            ->where('validated_at', null);
    }

    /**
     * Get the user's projects
     */
    public function projects(): BelongsToMany
    {
        return $this->belongsToMany(Project::class, Member::class);
    }

    public function follows(): BelongsToMany
    {
        return $this->belongsToMany(User::class, UserFollow::class);
    }

    /**
     * The user's preferred app language (distinct from user_preferences' spoken-languages list).
     */
    public function language(): BelongsTo
    {
        return $this->belongsTo(Language::class);
    }

    /**
     * The user's app locale, resolved from their preferred language.
     * Null when unset, or when the preferred language isn't one the app has translations for.
     */
    public function locale(): ?string
    {
        $code = $this->language ? strtolower($this->language->name) : null;

        return in_array($code, config('app.locales'), true) ? $code : null;
    }

    public function notificationPreferences(): HasMany
    {
        return $this->hasMany(NotificationPreference::class);
    }

    /**
     * Whether the user wants to receive email for a given notification type.
     * Defaults to true when no preference row exists yet.
     */
    public function wantsEmailFor(NotificationType $type): bool
    {
        return $this->notificationPreferences()->where('type', $type->value)->value('email_enabled') ?? true;
    }

    // TODO Should be policy
    public static function canFindUser($userId, User $currentUser): ?User
    {
        $user = User::find($userId);

        if (! $user) {
            return null;
        }

        //        if ($user->is_private) {
        // Check if user has projects in common or public projects
        //        }

        return $user;
    }

    public function followAs(User $user)
    {
        // Space for blocked users rules
        if (false) {
            return false;
        }
        if (UserFollow::where('user_id', $user->id)->where('followed_user_id', $this->id)->exists()) {
            return false;
        }

        UserFollow::create([
            'user_id' => $user->id,
            'followed_user_id' => $this->id,
        ]);

        return true;
    }

    public function unfollowAs(User $user)
    {
        if (($userFollow = UserFollow::where('user_id', $user->id)->where('followed_user_id', $this->id))->exists()) {
            $userFollow->delete();

            return true;
        }

        return false;
    }
}
